// Generated by gencpp from file drift_car/Action.msg
// DO NOT EDIT!


#ifndef DRIFT_CAR_MESSAGE_ACTION_H
#define DRIFT_CAR_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drift_car
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : header()
    , steering_angle(0.0)
    , throttle(0.0)  {
    }
  Action_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering_angle(0.0)
    , throttle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef double _throttle_type;
  _throttle_type throttle;




  typedef boost::shared_ptr< ::drift_car::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drift_car::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::drift_car::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::drift_car::Action > ActionPtr;
typedef boost::shared_ptr< ::drift_car::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drift_car::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drift_car::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drift_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'drift_car': ['/home/kanak/fyp_ws/src/drift_car/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drift_car::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drift_car::Action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drift_car::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drift_car::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drift_car::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drift_car::Action_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drift_car::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4d5434aed0e942aaba81c50637751a2";
  }

  static const char* value(const ::drift_car::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4d5434aed0e942aULL;
  static const uint64_t static_value2 = 0xaba81c50637751a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::drift_car::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drift_car/Action";
  }

  static const char* value(const ::drift_car::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drift_car::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 steering_angle\n\
float64 throttle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drift_car::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drift_car::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering_angle);
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drift_car::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drift_car::Action_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIFT_CAR_MESSAGE_ACTION_H
