/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Feb 26 16:39:04 2018. */

#ifndef PB_FYP_MESSAGES_PB_H_INCLUDED
#define PB_FYP_MESSAGES_PB_H_INCLUDED
#include "pb.h"


/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _fyp_Action {
    int32_t throttle;
    float steering;
/* @@protoc_insertion_point(struct:fyp_Action) */
} fyp_Action;

typedef struct _fyp_State {
    float x;
    float y;
    float theta;
    float xDot;
    float yDot;
    float thetaDot;
/* @@protoc_insertion_point(struct:fyp_State) */
} fyp_State;

/* Default values for struct fields */

/* Initializer values for message structs */
#define fyp_Action_init_default                  {0, 0}
#define fyp_State_init_default                   {0, 0, 0, 0, 0, 0}
#define fyp_Action_init_zero                     {0, 0}
#define fyp_State_init_zero                      {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define fyp_Action_throttle_tag                  1
#define fyp_Action_steering_tag                  2
#define fyp_State_x_tag                          1
#define fyp_State_y_tag                          2
#define fyp_State_theta_tag                      3
#define fyp_State_xDot_tag                       4
#define fyp_State_yDot_tag                       5
#define fyp_State_thetaDot_tag                   6

/* Struct field encoding specification for nanopb */
extern const pb_field_t fyp_Action_fields[3];
extern const pb_field_t fyp_State_fields[7];

/* Maximum encoded size of messages (where known) */
#define fyp_Action_size                          16
#define fyp_State_size                           30

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif

