/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Feb 26 16:39:04 2018. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fyp_Action_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, fyp_Action, throttle, throttle, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, fyp_Action, steering, throttle, 0),
    PB_LAST_FIELD
};

const pb_field_t fyp_State_fields[7] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, fyp_State, x, x, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, fyp_State, y, x, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, fyp_State, theta, y, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, fyp_State, xDot, theta, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, fyp_State, yDot, xDot, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, fyp_State, thetaDot, yDot, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */

